stages:
  preprocess:
    cmd: python training/preprocess.py --input_data ./data/census.csv --output_data
      ./data/preprocess.csv
    deps:
    - data/census.csv
    - training/preprocess.py
    params:
    - param
    outs:
    - data/preprocess.csv
