stages:
  preprocess:
    cmd: python training/preprocess.py
    deps:
    - data/census.csv
    - training/preprocess.py
    outs:
    - data/preprocess.csv
  training:
    cmd: python training/training.py --force
    deps:
    - data/preprocess.csv
    - training/train_model.py
    params:
    - random_forest.arams.n_estimators
    - random_forest.arams.max_depth
    - random_forest.arams.min_samples_split
    outs:
    - model/random_forest_census_income.joblib
    - model/scores.json
