stages:
  preprocess:
    cmd: python training/preprocess.py
    deps:
    - data/census.csv
    - training/preprocess.py
    outs:
    - data/preprocess.csv
  training:
    cmd: python training/train_model.py
    deps:
    - data/preprocess.csv
    - training/train_model.py
    params:
    - random_forest.params.n_estimators
    - random_forest.params.max_depth
    - random_forest.params.min_samples_split
    outs:
    - model/random_forest_census_income.joblib
    metrics:
      - model/scores.json
