input_data: ./data/census.csv
preproccess_output_path: ./data/preprocess.csv
random_forest:
  params:
    n_estimators: 300
    criterion: 'gini'
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: -1
    random_state: 42
  features:
    categorical:
      - "workclass"
      - "education"
      - "marital-status"
      - "occupation"
      - "relationship"
      - "race"
      - "sex"
      - "native-country"
  export_name: "random_forest_census_income"