input_data: ./data/census.csv
preproccess_output_path: ./data/preprocess.csv
random_forest:
  params:
    n_estimators: 100
    criterion: 'gini'
    max_depth: 13
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: null
    random_state: 42
    verbose: 0
    warm_start: false
    class_weight: "balanced"
    ccp_alpha: 0.0
    max_samples: null
  features:
    categorical:
      - "workclass"
      - "education"
      - "marital-status"
      - "occupation"
      - "relationship"
      - "race"
      - "sex"
      - "native-country"
  export_name: "random_forest_census_income"